MODEL_PATH = "./model.pkl"
PREDICTION_LENGTH = 275
PREDICTION_PATH = "./prediction.txt"
INITIAL_PATH = "./initial.txt"
MINI_BATCH_SIZE = 100
LENGTH_OF_SEQUENCE = 300
STEPS_PER_CYCLE = 50
NUMBER_OF_CYCLES = 100

IN_UNITS = 2
HIDDEN_UNITS = 4
OUT_UNITS = 1
TRAINING_EPOCHS = 4000
DISPLAY_EPOCH = 10
